.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. merit_qt test_merit_qt
clean: FORCE
	$(MAKE) -C .. merit_qt_clean test_merit_qt_clean
check: FORCE
	$(MAKE) -C .. test_merit_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. merit_qt
