// Copyright (c) 2014-2017 The Merit Foundation developers
#ifndef MERIT_CHAINPARAMSSEEDS_H
#define MERIT_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the merit network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x43,0x28,0xcf,0x83}, 8445},
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x43,0x28,0xcf,0x85}, 8445}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // MERIT_CHAINPARAMSSEEDS_H

